### ISSUE TITLE
[Propose] Command (Numbered) Postfix

### ISSUE THREAD

**Issue by malformed-c** [cancelledbit/pizda_bot#13]
Implement a number postfix for commands to send multiple phrases in one message, max 3 phrases

### Example
`/hzN` or `/hz N` where N 3 or less
will send three phrases in one message

`/hzN` or `/hz N` where N 4 or more
will send 1 phrase

### Rationale
To stop spam in chat because many people want a complete sentence out of bot and send multiple commands in a row

**Comment by cancelledbit** [comment]
`/hzN` - not implemented due to lack of sane

`/hz N` where N > 3 will return 3 phrases, otherwise N phrases. 

`/hz` returns 1 phrase
